language: go
sudo: false

go:
  - 1.6.x
  - 1.7.x
  - tip

services:
  - redis
  - docker

before_install:
  - docker run -p 3307:3306 -e MYSQL_DATABASE=app -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql
  - mysql -u root -h 127.0.0.1 -P 3307 -e 'SHOW DATABASES;'

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: false
