language: go
sudo: false

go:
  - 1.6.x
  - 1.7.x
  - tip

services:
  - redis
  - docker

before_install:
  # - mysql -u root -e "SET PASSWORD FOR root@localhost = PASSWORD('');"
  # - mysql -u root -e "SET PASSWORD FOR root@127.0.0.1 = PASSWORD('');"
  - docker run --name mysql -p 3307:3306 -e MYSQL_ROOT_PASSWORD=1234 -d mysql
  - mysql -u root -p1234 -P 3307 -e 'CREATE DATABASE myapp;'

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: false
